import type { NiwaState, Iteration, DimensionScores } from '../types/niwa';

const dims = (b: number, s: number, g: number, n: number, c: number, o: number): DimensionScores => ({
  balance: b, spacing: s, grouping: g, negative_space: n, color_harmony: c, overall: o,
});

const mockIterations: Iteration[] = [
  {
    id: 1, timestamp: '2026-03-15T13:31:00Z',
    critic: {
      priority: 'I care most about balance because the arrangement has no structure yet.',
      scores: dims(22, 18, 15, 30, 12, 19),
      suggestion: { block_color: 'pink', block_id: 'p1', from_position: 0, to_position: 4, orientation: 'flat' },
      reasoning: 'All blocks are piled in corner. Moving pink block to center creates initial balance axis.',
      artist_feedback: 'No previous Artist moves to evaluate.',
    },
    artist: {
      instinct: 'No patterns learned yet. Following Critic guidance.',
      move: { block_color: 'pink', block_id: 'p1', from_position: 0, to_position: 4, orientation: 'flat' },
      predicted_delta: 5, followed_critic: true,
    },
    actual_delta: 8, overall_score: 19,
    dimension_scores: dims(22, 18, 15, 30, 12, 19),
    priority_changed: false, instinct_changed: false,
  },
  {
    id: 2, timestamp: '2026-03-15T13:32:00Z',
    critic: {
      priority: 'I care most about balance because centering the first block improved structure.',
      scores: dims(31, 22, 18, 28, 15, 24),
      suggestion: { block_color: 'green', block_id: 'g1', from_position: 1, to_position: 6, orientation: 'vertical' },
      reasoning: 'Balance improved significantly. Now create vertical tension with green block on left edge.',
      artist_feedback: 'Artist followed suggestion. Score improved by 8 points. Good compliance.',
    },
    artist: {
      instinct: 'Center placements seem effective. Trying Critic\'s vertical suggestion.',
      move: { block_color: 'green', block_id: 'g1', from_position: 1, to_position: 6, orientation: 'vertical' },
      predicted_delta: 6, followed_critic: true,
    },
    actual_delta: 5, overall_score: 24,
    dimension_scores: dims(31, 22, 18, 28, 15, 24),
    priority_changed: false, instinct_changed: true,
  },
  {
    id: 3, timestamp: '2026-03-15T13:33:00Z',
    critic: {
      priority: 'I care most about spacing because the blocks are too clustered on one side.',
      scores: dims(35, 20, 22, 25, 20, 26),
      suggestion: { block_color: 'blue', block_id: 'b1', from_position: 2, to_position: 8, orientation: 'flat' },
      reasoning: 'Balance plateau reached. Spacing is now the weakest dimension. Distribute blue to far corner.',
      artist_feedback: 'Artist followed. Delta prediction was off by 1. Developing accuracy.',
    },
    artist: {
      instinct: 'Vertical placements create visual interest. But Critic wants distribution now.',
      move: { block_color: 'blue', block_id: 'b1', from_position: 2, to_position: 8, orientation: 'on-side' },
      predicted_delta: 4, followed_critic: false,
      rejection_reasoning: 'Critic suggested flat but on-side creates better visual weight distribution at edges.',
    },
    actual_delta: 6, overall_score: 30,
    dimension_scores: dims(35, 26, 22, 25, 20, 26),
    priority_changed: true, instinct_changed: false,
  },
  {
    id: 4, timestamp: '2026-03-15T13:34:00Z',
    critic: {
      priority: 'I now care most about spacing because the on-side placement improved distribution significantly.',
      scores: dims(38, 34, 25, 30, 22, 32),
      suggestion: { block_color: 'pink', block_id: 'p2', from_position: 3, to_position: 2, orientation: 'flat' },
      reasoning: 'Artist\'s rejection improved spacing by 6 not 2. Their on-side instinct was right. Adjusting my suggestions.',
      artist_feedback: 'Artist rejected flat for on-side. Score jumped 6 points. Acknowledging Artist\'s spatial instinct.',
    },
    artist: {
      instinct: 'On-side placements at edges score higher than flat ones. My spatial intuition is developing.',
      move: { block_color: 'pink', block_id: 'p2', from_position: 3, to_position: 2, orientation: 'on-side' },
      predicted_delta: 5, followed_critic: false,
      rejection_reasoning: 'Applying learned instinct: on-side at positions 2,6,8 outperforms flat. Overriding Critic again.',
    },
    actual_delta: 7, overall_score: 37,
    dimension_scores: dims(38, 34, 25, 30, 22, 32),
    priority_changed: false, instinct_changed: true,
  },
  {
    id: 5, timestamp: '2026-03-15T13:35:00Z',
    critic: {
      priority: 'I now care most about color_harmony because the spatial arrangement is solid but colors are random.',
      scores: dims(40, 38, 30, 32, 18, 34),
      suggestion: { block_color: 'green', block_id: 'g2', from_position: 5, to_position: 7, orientation: 'vertical' },
      reasoning: 'Spatial dimensions plateau. Color harmony is now the biggest gap. Group green blocks for color coherence.',
      artist_feedback: 'Artist rejected again and improved. Starting to trust their orientation instincts.',
    },
    artist: {
      instinct: 'I\'ve learned that edge on-side beats flat by ~3 points. Now noticing color groupings affect my predictions.',
      move: { block_color: 'green', block_id: 'g2', from_position: 5, to_position: 7, orientation: 'vertical' },
      predicted_delta: 4, followed_critic: true,
    },
    actual_delta: 5, overall_score: 39,
    dimension_scores: dims(40, 38, 30, 32, 25, 34),
    priority_changed: true, instinct_changed: true,
  },
  {
    id: 6, timestamp: '2026-03-15T13:36:00Z',
    critic: {
      priority: 'Color harmony is now my top priority. Grouping similar colors creates visual coherence the arrangement lacked.',
      scores: dims(42, 40, 35, 34, 32, 38),
      suggestion: { block_color: 'blue', block_id: 'b2', from_position: 4, to_position: 5, orientation: 'on-side' },
      reasoning: 'Green grouping worked. Now cluster blue blocks. Artist should appreciate the on-side suggestion this time.',
      artist_feedback: 'Artist followed my vertical suggestion. We agree on color grouping strategy now.',
    },
    artist: {
      instinct: 'Color adjacency matters more than I initially weighted. Critic and I are converging on color clusters.',
      move: { block_color: 'blue', block_id: 'b2', from_position: 4, to_position: 5, orientation: 'on-side' },
      predicted_delta: 4, followed_critic: true,
    },
    actual_delta: 3, overall_score: 41,
    dimension_scores: dims(42, 40, 35, 34, 32, 38),
    priority_changed: false, instinct_changed: true,
  },
  {
    id: 7, timestamp: '2026-03-15T13:37:00Z',
    critic: {
      priority: 'Grouping is now my focus. Color clusters are forming but the grouping score lags behind.',
      scores: dims(44, 42, 32, 36, 38, 40),
      suggestion: { block_color: 'pink', block_id: 'p3', from_position: 7, to_position: 3, orientation: 'flat' },
      reasoning: 'Blues clustered. Now group pinks. Moving pink to position 3 creates pink triangle with positions 2 and 4.',
      artist_feedback: 'Artist used on-side as I suggested. Prediction off by 1. Understanding growing.',
    },
    artist: {
      instinct: 'Triangle formations with same-color blocks score well for grouping. Testing this pattern.',
      move: { block_color: 'pink', block_id: 'p3', from_position: 7, to_position: 3, orientation: 'vertical' },
      predicted_delta: 5, followed_critic: false,
      rejection_reasoning: 'Flat would break the visual rhythm. Vertical maintains the height variation I\'ve been building.',
    },
    actual_delta: 6, overall_score: 46,
    dimension_scores: dims(44, 42, 38, 36, 38, 40),
    priority_changed: true, instinct_changed: false,
  },
  {
    id: 8, timestamp: '2026-03-15T13:38:00Z',
    critic: {
      priority: 'I\'m shifting to negative_space. The arrangement is filling up and needs breathing room.',
      scores: dims(46, 44, 42, 32, 42, 44),
      suggestion: { block_color: 'green', block_id: 'g3', from_position: 6, to_position: 1, orientation: 'flat' },
      reasoning: 'Grouping jumped after pink triangle. But negative space is suffering. Move green to create gap.',
      artist_feedback: 'Artist chose vertical over flat. Score jumped 6. Their height instinct is proven.',
    },
    artist: {
      instinct: 'Height variation is core to my aesthetic. Flat placements feel wrong now. I predict the gap needs maintaining.',
      move: { block_color: 'green', block_id: 'g3', from_position: 6, to_position: 1, orientation: 'on-side' },
      predicted_delta: 3, followed_critic: false,
      rejection_reasoning: 'Flat at position 1 would fill the space too much. On-side preserves negative space better.',
    },
    actual_delta: 4, overall_score: 48,
    dimension_scores: dims(46, 44, 42, 36, 42, 44),
    priority_changed: true, instinct_changed: true,
  },
  {
    id: 9, timestamp: '2026-03-15T13:39:00Z',
    critic: {
      priority: 'Negative space and overall balance. The arrangement is approaching aesthetic coherence.',
      scores: dims(48, 46, 44, 40, 44, 46),
      suggestion: { block_color: 'blue', block_id: 'b3', from_position: 8, to_position: 6, orientation: 'vertical' },
      reasoning: 'Near convergence. Blue at corner is isolated. Bring it to create final color cluster.',
      artist_feedback: 'Artist preserved negative space with on-side. We\'re starting to think alike on spatial layout.',
    },
    artist: {
      instinct: 'The arrangement wants a focal point. Blue vertical at position 6 would anchor the composition.',
      move: { block_color: 'blue', block_id: 'b3', from_position: 8, to_position: 6, orientation: 'vertical' },
      predicted_delta: 4, followed_critic: true,
    },
    actual_delta: 5, overall_score: 51,
    dimension_scores: dims(48, 46, 44, 40, 44, 46),
    priority_changed: false, instinct_changed: false,
  },
  {
    id: 10, timestamp: '2026-03-15T13:40:00Z',
    critic: {
      priority: 'Color harmony and overall. We\'re refining now, not restructuring. The taste has emerged.',
      scores: dims(50, 48, 46, 44, 48, 50),
      suggestion: { block_color: 'pink', block_id: 'p4', from_position: 0, to_position: 5, orientation: 'on-side' },
      reasoning: 'Refinement phase. Last isolated pink needs to join its cluster. Arrangement has developed a clear aesthetic.',
      artist_feedback: 'Full agreement on last move. Prediction accuracy at 1 point delta. We understand each other.',
    },
    artist: {
      instinct: 'I can predict the Critic within 1 point now. Our aesthetics have converged. On-side feels right for this position.',
      move: { block_color: 'pink', block_id: 'p4', from_position: 0, to_position: 5, orientation: 'on-side' },
      predicted_delta: 5, followed_critic: true,
    },
    actual_delta: 4, overall_score: 54,
    dimension_scores: dims(50, 48, 46, 44, 48, 50),
    priority_changed: true, instinct_changed: true,
  },
];

export const MOCK_STATE: NiwaState = {
  status: 'running',
  current_iteration: 10,
  iterations: mockIterations,
  overall_score: 54,
  latest_image: undefined,
  initial_priorities: dims(50, 30, 20, 15, 10, 25),
  current_priorities: dims(30, 25, 25, 22, 48, 50),
  prediction_accuracy: [3, 1, 2, 2, 1, 1, 1, 1, 1, 1],
  follow_rate: [1, 1, 0.67, 0.5, 0.6, 0.67, 0.57, 0.5, 0.56, 0.6],
  active_dimensions: ['balance', 'spacing', 'grouping', 'negative_space', 'color_harmony', 'overall'],
  cloud_endpoint: 'https://niwa.nebius.cloud/api',
  model_critic: 'Qwen2.5-VL-72B',
  model_artist: 'Gemma-3-27B',
  robot_status: 'idle',
  robot_hardware: {
    connection: 'streaming',
    joint_positions: {
      'shoulder_pan.pos': 45.2,
      'shoulder_lift.pos': -12.8,
      'elbow_flex.pos': 67.5,
      'wrist_flex.pos': -22.1,
      'wrist_roll.pos': 90.0,
      'gripper.pos': 35.0,
    },
    joint_targets: undefined,
    action_queue_size: 12,
    action_chunk_size: 50,
    fps_actual: 28.5,
    fps_target: 30,
    last_action_timestep: 847,
    calibrated: true,
    trajectories_loaded: 16,
    current_trajectory: undefined,
  },
  policy_server: {
    host: 'niwa-gpu.nebius.cloud',
    port: 8080,
    fps: 30,
    inference_latency: 0.033,
    obs_queue_timeout: 1,
  },
  robot_client: {
    robot_type: 'so101_follower',
    robot_id: 'niwa-arm',
    server_address: 'niwa-gpu.nebius.cloud:8080',
    policy_type: 'act',
    actions_per_chunk: 50,
    chunk_size_threshold: 0.5,
    policy_device: 'cuda',
    client_device: 'cpu',
  },
};

export const EMPTY_STATE: NiwaState = {
  status: 'paused',
  current_iteration: 0,
  iterations: [],
  overall_score: 0,
  latest_image: undefined,
  initial_priorities: dims(50, 30, 20, 15, 10, 25),
  current_priorities: dims(50, 30, 20, 15, 10, 25),
  prediction_accuracy: [],
  follow_rate: [],
  active_dimensions: ['balance', 'spacing', 'grouping', 'negative_space', 'color_harmony', 'overall'],
  cloud_endpoint: 'https://niwa.nebius.cloud/api',
  model_critic: 'Qwen2.5-VL-72B',
  model_artist: 'Gemma-3-27B',
  robot_status: 'idle',
  robot_hardware: {
    connection: 'disconnected',
    joint_positions: {
      'shoulder_pan.pos': 0, 'shoulder_lift.pos': 0, 'elbow_flex.pos': 0,
      'wrist_flex.pos': 0, 'wrist_roll.pos': 0, 'gripper.pos': 0,
    },
    joint_targets: undefined,
    action_queue_size: 0,
    action_chunk_size: 50,
    fps_actual: 0,
    fps_target: 30,
    last_action_timestep: 0,
    calibrated: false,
    trajectories_loaded: 0,
    current_trajectory: undefined,
  },
};
