import type { NiwaState, Iteration, DimensionScores } from '../types/niwa';

const dims = (st: number, bl: number, rl: number, ms: number, o: number): DimensionScores => ({
  stability: st, block_looseness: bl, risk_level: rl, move_success: ms, overall: o,
});

const mockIterations: Iteration[] = [
  {
    id: 1, timestamp: '2026-03-15T10:41:00Z',
    critic: {
      priority: 'Stability matters most — this is a fresh tower, need to assess initial state.',
      scores: dims(92, 45, 8, 50, 65),
      suggestion: { target_row: 6, target_position: 'middle', push_direction: 'left_to_right', push_force: 'gentle', approach_speed: 'slow' },
      reasoning: 'Fresh tower. Row 6 middle block appears slightly loose. Starting cautious.',
      artist_feedback: 'No previous Strategist moves to evaluate.',
    },
    artist: {
      instinct: 'No patterns learned yet. Following Critic guidance.',
      move: { target_row: 6, target_position: 'middle', push_direction: 'left_to_right', push_force: 'gentle', approach_speed: 'slow' },
      predicted_delta: 3, followed_critic: true,
    },
    actual_delta: 5, overall_score: 65,
    dimension_scores: dims(92, 45, 8, 50, 65),
    priority_changed: false, instinct_changed: false,
  },
  {
    id: 2, timestamp: '2026-03-15T10:42:00Z',
    critic: {
      priority: 'Move success is key — first push went clean, keep building on that.',
      scores: dims(88, 50, 12, 78, 70),
      suggestion: { target_row: 8, target_position: 'middle', push_direction: 'left_to_right', push_force: 'gentle', approach_speed: 'slow' },
      reasoning: 'Clean first push. Tower barely moved. Row 8 middle also shows a gap.',
      artist_feedback: 'Strategist followed suggestion. Clean extraction. Stability only dipped 4 points.',
    },
    artist: {
      instinct: 'Middle blocks push cleanly. Gentle force works. Staying conservative.',
      move: { target_row: 8, target_position: 'middle', push_direction: 'left_to_right', push_force: 'gentle', approach_speed: 'slow' },
      predicted_delta: 4, followed_critic: true,
    },
    actual_delta: 6, overall_score: 70,
    dimension_scores: dims(88, 50, 12, 78, 70),
    priority_changed: true, instinct_changed: true,
  },
  {
    id: 3, timestamp: '2026-03-15T10:43:00Z',
    critic: {
      priority: 'Block looseness — more blocks are becoming pushable as the tower settles.',
      scores: dims(85, 58, 15, 82, 73),
      suggestion: { target_row: 5, target_position: 'left', push_direction: 'right_to_left', push_force: 'medium', approach_speed: 'slow' },
      reasoning: 'Two clean pushes. Left block at row 5 protrudes slightly. Suggest right-to-left.',
      artist_feedback: 'Strategist followed. Delta prediction off by 2. Developing accuracy.',
    },
    artist: {
      instinct: 'Middle blocks at rows 6-8 are safe. Testing a side block now — Critic sees protrusion.',
      move: { target_row: 5, target_position: 'left', push_direction: 'right_to_left', push_force: 'gentle', approach_speed: 'slow' },
      predicted_delta: 3, followed_critic: false,
      rejection_reasoning: 'Critic said medium force but I think gentle is safer for a side block.',
    },
    actual_delta: 7, overall_score: 77,
    dimension_scores: dims(85, 58, 15, 82, 73),
    priority_changed: true, instinct_changed: false,
  },
  {
    id: 4, timestamp: '2026-03-15T10:44:00Z',
    critic: {
      priority: 'Stability — tower shifted slightly on last push. Need to be more careful with side blocks.',
      scores: dims(80, 62, 20, 75, 72),
      suggestion: { target_row: 7, target_position: 'middle', push_direction: 'left_to_right', push_force: 'gentle', approach_speed: 'slow' },
      reasoning: 'Side block push worked but tower wobbled. Back to middle blocks for safety.',
      artist_feedback: 'Strategist reduced force from my suggestion. Smart — gentler push actually scored higher.',
    },
    artist: {
      instinct: 'Gentle force consistently outperforms medium. Side blocks need extra caution.',
      move: { target_row: 7, target_position: 'middle', push_direction: 'left_to_right', push_force: 'gentle', approach_speed: 'slow' },
      predicted_delta: 4, followed_critic: true,
    },
    actual_delta: 5, overall_score: 75,
    dimension_scores: dims(80, 62, 20, 75, 72),
    priority_changed: true, instinct_changed: true,
  },
  {
    id: 5, timestamp: '2026-03-15T10:45:00Z',
    critic: {
      priority: 'Risk level creeping up — need to choose blocks that stabilize the tower.',
      scores: dims(82, 55, 22, 80, 74),
      suggestion: { target_row: 9, target_position: 'middle', push_direction: 'left_to_right', push_force: 'gentle', approach_speed: 'slow' },
      reasoning: 'Middle blocks remain safest. Row 9 has a visible gap. Risk is manageable.',
      artist_feedback: 'Return to middle was smart. Clean push, good recovery.',
    },
    artist: {
      instinct: 'Rows 5-9 middle blocks with gentle force is my winning formula. 4/4 clean pushes there.',
      move: { target_row: 9, target_position: 'middle', push_direction: 'left_to_right', push_force: 'gentle', approach_speed: 'slow' },
      predicted_delta: 5, followed_critic: true,
    },
    actual_delta: 4, overall_score: 78,
    dimension_scores: dims(82, 55, 22, 80, 74),
    priority_changed: true, instinct_changed: true,
  },
  {
    id: 6, timestamp: '2026-03-15T10:46:00Z',
    critic: {
      priority: 'Move success — maintaining the streak of clean pushes matters most now.',
      scores: dims(79, 60, 25, 85, 78),
      suggestion: { target_row: 4, target_position: 'middle', push_direction: 'left_to_right', push_force: 'gentle', approach_speed: 'slow' },
      reasoning: 'Lower rows are more stable for pushing. Row 4 middle should be safe.',
      artist_feedback: 'Strategist consistent with middle-gentle strategy. Prediction accuracy improving.',
    },
    artist: {
      instinct: 'Middle-gentle is proven. But I notice lower rows give better stability scores post-push.',
      move: { target_row: 4, target_position: 'middle', push_direction: 'left_to_right', push_force: 'gentle', approach_speed: 'slow' },
      predicted_delta: 4, followed_critic: true,
    },
    actual_delta: 5, overall_score: 80,
    dimension_scores: dims(79, 60, 25, 85, 78),
    priority_changed: true, instinct_changed: true,
  },
  {
    id: 7, timestamp: '2026-03-15T10:47:00Z',
    critic: {
      priority: 'Block looseness — running low on easy middle blocks. Need to start targeting side positions.',
      scores: dims(76, 42, 28, 82, 76),
      suggestion: { target_row: 10, target_position: 'right', push_direction: 'left_to_right', push_force: 'medium', approach_speed: 'slow' },
      reasoning: 'Middle blocks depleting in reachable rows. Right block at row 10 looks loose.',
      artist_feedback: 'Strategist shows strong middle-block pattern. May need to adapt as middles run out.',
    },
    artist: {
      instinct: 'Critic wants to go to side blocks. But my data says gentle middle > medium side. Testing a compromise.',
      move: { target_row: 10, target_position: 'right', push_direction: 'left_to_right', push_force: 'gentle', approach_speed: 'slow' },
      predicted_delta: 3, followed_critic: false,
      rejection_reasoning: 'Accepting the target but reducing force. My rejection of medium force has been validated.',
    },
    actual_delta: 6, overall_score: 82,
    dimension_scores: dims(76, 42, 28, 82, 76),
    priority_changed: true, instinct_changed: false,
  },
  {
    id: 8, timestamp: '2026-03-15T10:48:00Z',
    critic: {
      priority: 'Risk level — tower is getting tall on one side from removed blocks. Prioritize balance.',
      scores: dims(73, 45, 32, 88, 80),
      suggestion: { target_row: 6, target_position: 'right', push_direction: 'left_to_right', push_force: 'gentle', approach_speed: 'slow' },
      reasoning: 'Strategist was right about gentle force on side blocks. Adopting that approach.',
      artist_feedback: 'Strategist overrode my force suggestion and got higher move_success. Updating my model.',
    },
    artist: {
      instinct: 'Gentle force works on side blocks too. Force is more important than position. Keeping everything gentle.',
      move: { target_row: 6, target_position: 'right', push_direction: 'left_to_right', push_force: 'gentle', approach_speed: 'slow' },
      predicted_delta: 4, followed_critic: true,
    },
    actual_delta: 3, overall_score: 82,
    dimension_scores: dims(73, 45, 32, 88, 80),
    priority_changed: true, instinct_changed: true,
  },
  {
    id: 9, timestamp: '2026-03-15T10:49:00Z',
    critic: {
      priority: 'Overall game quality — we have a strong pattern now. Stay consistent.',
      scores: dims(70, 48, 35, 90, 82),
      suggestion: { target_row: 5, target_position: 'right', push_direction: 'right_to_left', push_force: 'gentle', approach_speed: 'slow' },
      reasoning: 'Tower stable despite 8 removals. Row 5 right block has shifted from earlier pushes.',
      artist_feedback: 'Full agreement on gentle force. Prediction accuracy converging.',
    },
    artist: {
      instinct: 'I can predict the Critic within 1-2 points. We agree gentle is always right. Row selection is the key variable now.',
      move: { target_row: 5, target_position: 'right', push_direction: 'right_to_left', push_force: 'gentle', approach_speed: 'slow' },
      predicted_delta: 3, followed_critic: true,
    },
    actual_delta: 4, overall_score: 85,
    dimension_scores: dims(70, 48, 35, 90, 82),
    priority_changed: true, instinct_changed: false,
  },
  {
    id: 10, timestamp: '2026-03-15T10:50:00Z',
    critic: {
      priority: 'Stability and overall — 9 successful pushes. The learned pattern is working.',
      scores: dims(68, 50, 38, 92, 85),
      suggestion: { target_row: 7, target_position: 'left', push_direction: 'right_to_left', push_force: 'gentle', approach_speed: 'slow' },
      reasoning: 'Remarkable run. Tower still standing after 9 pushes. Our gentle-first strategy is proven.',
      artist_feedback: 'Strategist and I have converged. Prediction error < 2. Mutual understanding achieved.',
    },
    artist: {
      instinct: 'Gentle force, mid-range rows, read the gaps. 9/9 successful pushes. The tower is still standing.',
      move: { target_row: 7, target_position: 'left', push_direction: 'right_to_left', push_force: 'gentle', approach_speed: 'slow' },
      predicted_delta: 4, followed_critic: true,
    },
    actual_delta: 3, overall_score: 88,
    dimension_scores: dims(68, 50, 38, 92, 85),
    priority_changed: true, instinct_changed: true,
  },
];

export const MOCK_STATE: NiwaState = {
  status: 'running',
  current_iteration: 10,
  iterations: mockIterations,
  overall_score: 88,
  latest_image: undefined,
  initial_priorities: dims(90, 45, 10, 50, 65),
  current_priorities: dims(68, 50, 38, 92, 85),
  prediction_accuracy: [2, 2, 4, 1, 1, 1, 3, 1, 1, 1],
  follow_rate: [1, 1, 0.67, 0.75, 0.8, 0.83, 0.71, 0.75, 0.78, 0.8],
  active_dimensions: ['stability', 'block_looseness', 'risk_level', 'move_success', 'overall'],
  cloud_endpoint: 'https://niwa.nebius.cloud/api',
  model_critic: 'Qwen2.5-VL-72B',
  model_artist: 'Gemma-3-27B',
  robot_status: 'idle',
  robot_hardware: {
    connection: 'streaming',
    joint_positions: {
      'shoulder_pan': 0,
      'shoulder_lift': -45,
      'elbow_flex': 90,
      'wrist_flex': 0,
      'wrist_roll': 0,
      'gripper': 0,
    },
    joint_targets: undefined,
    action_queue_size: 8,
    action_chunk_size: 50,
    fps_actual: 28.5,
    fps_target: 30,
    last_action_timestep: 847,
    calibrated: true,
    trajectories_loaded: 12,
    current_trajectory: undefined,
  },
  policy_server: {
    host: 'niwa-gpu.nebius.cloud',
    port: 8080,
    fps: 30,
    inference_latency: 0.033,
    obs_queue_timeout: 1,
  },
  robot_client: {
    robot_type: 'so101_follower',
    robot_id: 'niwa-jenga',
    server_address: 'niwa-gpu.nebius.cloud:8080',
    policy_type: 'act',
    actions_per_chunk: 50,
    chunk_size_threshold: 0.5,
    policy_device: 'cuda',
    client_device: 'cpu',
  },
};

export const EMPTY_STATE: NiwaState = {
  status: 'paused',
  current_iteration: 0,
  iterations: [],
  overall_score: 0,
  latest_image: undefined,
  initial_priorities: dims(90, 45, 10, 50, 65),
  current_priorities: dims(90, 45, 10, 50, 65),
  prediction_accuracy: [],
  follow_rate: [],
  active_dimensions: ['stability', 'block_looseness', 'risk_level', 'move_success', 'overall'],
  cloud_endpoint: 'https://niwa.nebius.cloud/api',
  model_critic: 'Qwen2.5-VL-72B',
  model_artist: 'Gemma-3-27B',
  robot_status: 'idle',
  robot_hardware: {
    connection: 'disconnected',
    joint_positions: {
      'shoulder_pan': 0, 'shoulder_lift': 0, 'elbow_flex': 0,
      'wrist_flex': 0, 'wrist_roll': 0, 'gripper': 0,
    },
    joint_targets: undefined,
    action_queue_size: 0,
    action_chunk_size: 50,
    fps_actual: 0,
    fps_target: 30,
    last_action_timestep: 0,
    calibrated: false,
    trajectories_loaded: 0,
    current_trajectory: undefined,
  },
};
